name: End-to-end tests 🧪

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm install
          start: npm start
          wait-on: 'http://localhost:3000' # Se houver front local
          wait-on-timeout: 60
          command: npm run test

      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
