name: Cypress Tests with Allure Report

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run Cypress tests with Allure
        run: npm run test

      - name: Generate Allure Report
        run: npm run allure:generate

      - name: Upload Allure Report artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
